### ISSUE TITLE
Why is PSNR increase so small after 10,000 iterations?

### ISSUE THREAD

**Issue by lgupta-mle** [Xinjie-Q/GaussianImage#15]
Just wondering if there's a solid answer to why the PSNR increases so slowly after about 10,000 iterations. For numerical context, the PSNR touched 30 at 10,000 iterations with 1000 points but only 30.8 by the 50,000 iteration mark. Can something be done to improve fitting accuracy? Increasing the number of points increases PSNR but the same slow gains happen. after 10,000 iterations.

**Comment by Xinjie-Q** [comment]
Yes, there are some methods to improve the accuracy. This paper ("Image-GS: Content-Adaptive Image Representation via 2D Gaussians") proposes the error-based optimization and hierarchical spatial partitioning to effectively improve the accuracy of GaussianImage.

**Comment by lgupta-mle** [comment]
Thank you, I will have a look!

**Comment by djx99** [comment]
There doesn't seem to be a code for this paper ("Image-GS: Content-Adaptive Image Representation via 2D Gaussians") ?
