### ISSUE TITLE
Clarification on handling of out-of-bounds `self._features_dc` values during rendering

### ISSUE THREAD

**Issue by LonganWANG-cs** [Xinjie-Q/GaussianImage#18]
Hello,

I noticed that during model training, the color parameter `self._features_dc` for each Gaussian point is not constrained to the range (0,1), and in some cases, it takes on negative values or values greater than 1. Despite this, during rendering, `self._features_dc` is passed directly to `rasterize_forward_sum`. Strangely, such out-of-bounds values don't seem to cause any errors.

I couldn't find any code handling these values in the CUDA or model portions, even though in the model definition phase, you define `self.rgb_activation = torch.sigmoid`. However, in the property method:
```python
@property
def get_features(self):
    return self._features_dc
```
there is no application of any constraints. Could you please clarify how values outside the (0,1) range are being handled in this case?

Thank you!

**Comment by lwtai** [comment]
Hi, do you figure out this problem? I am also interested in the rendering process of this work
Does the cuda code renders a pixels simply by adding all values from gaussians covered on top?

**Comment by djx99** [comment]
Yes, I've noticed this as well. It doesn't seem to do any normalization, etc. after the accumulation. The formula for the paper is the same.
![image](https://github.com/user-attachments/assets/5917fac5-f543-435c-8fc6-14b12a1b737e)

**Comment by vitorpmh** [comment]
I was trying to visualise the gaussians colors individualy and step onto the same problem as you. I have tried to use arctan, arctanh, sigmoid inverse, minmaxscaling but i couldn't find a solution that gives the correct colour. 

@djx99 for me the problem here is calculating the sigma, they define it in the paper, but couldn't find the proper way to calculate the displacement.
