### ISSUE TITLE
when you say 3D GS only maintains Gaussians with a 99% confidence interval,do you mean there is no tiles in your work?

### ISSUE THREAD

**Issue by Ira569** [Xinjie-Q/GaussianImage#2]
does it mean only random_gauss_order rasterize，one gauss for all pixel? 
looking forward to your reply.

**Comment by Xinjie-Q** [comment]
No. In our implementation, we still restrict the range of each Gaussian as 3*sigma. Thus, a gaussian only covers a part of the image.

**Comment by djx99** [comment]
Specifically, whether the calculation of 3*sigma is based only on whether the largest outer circle is located in a tile, i.e., the implementation of the functions `get_bbox` and `get_tile_bbox`
