### ISSUE TITLE
Batch wise inference on images

### ISSUE THREAD

**Issue by ZiAngGu1** [Xinjie-Q/GaussianImage#4]
Hi there, thanks for the wonderful work, the performance is impressive. 
I just have a single question, if I get a set of image with the same height and width, would it be possible to do batch wise inference? if so how should I change the code?
Thanks for the response 
Sincerely,
ZiAng

**Comment by Xinjie-Q** [comment]
Yes, it is possible. You can use the batch-version gsplat (https://github.com/nerfstudio-project/gsplat/tree/batch) to implement the batch inference of GaussianImage.
