### ISSUE TITLE
Replication of Table1

### ISSUE THREAD

**Issue by djx99** [Xinjie-Q/GaussianImage#6]
Your work is excellent and I would like to ask what is the experimental setup for Table1 in the paper?

I ran sh . /scripts/gaussianimage_cholesky/kodak.sh /path/to/your/dataset command, and when num_points=9000, I can only get Average: 576*706, PSNR: 32.0501, MS-SSIM:0.9797, Trainging:29.9410s, Eval:0.00020857s, FPS:4803.6411

I'm running on ubuntu 18.04 pytorch2.0.1 GPU4090
Looking forward to your response :)

**Comment by Xinjie-Q** [comment]
The table 1 sets the number of gaussian points as 70k. Please change the num_points=70k and then you can replicate the results of table 1.

**Comment by djx99** [comment]
Thank you. I think the optimal number of points should be different for different sized images. Is this view correct? That is, have you tried to see if there is a proper ratio between the total number of pixels and num_points?

**Comment by Xinjie-Q** [comment]
Yes, the optimal number of points should be different for different sized images. I do not conduct this exploration experiment.

**Comment by renaissanceee** [comment]
Thanks for your reply. Actually, I find the quality metric of PSNR is very sensitive to num_of_points, i.e., 70k with 38dB and 6k with 30 dB. But more Gaussians also correspond to larger storage size, which is harmful for img compression task.
When setting the num_of_points to 70k (large number of Gaussians), the gaussian_model.best.pth.tar(e.g. 2MB) becomes even larger than original png img (e.g.1MB). Is it meaningful to conduct GaussianImage in such a condition?
