### ISSUE TITLE
Output render image of arbitrary resolution

### ISSUE THREAD

**Issue by djx99** [Xinjie-Q/GaussianImage#8]
Thanks for your work, I would like to know how to render images of other resolutions from the trained 2DGS. 
I tried to rewrite the `forward` function in `gaussianimage_cholesky.py` 
Change `self.H sel.W`  to input `H,W`. The code is as follows:

`def forward_HW(self, H, W):`
`    self.xys, depths, self.radii, conics, num_tiles_hit = project_gaussians_2d(self.get_xyz, self.get_cholesky_elements, H, W, self.tile_bounds)`
`     out_img = rasterize_gaussians_sum(self.xys, depths, self.radii, conics, num_tiles_hit, self.get_features, self._opacity, H, W, self.BLOCK_H, self.BLOCK_W, background=self.background, return_alpha=False)    `
`    out_img = torch.clamp(out_img, 0, 1) #[H, W, 3]`
`    out_img = out_img.view(-1, H, W, 3).permute(0, 3, 1, 2).contiguous()`
`    return {"render": out_img}`

However, when `H,W = self.H/2 sel.W/2`, the rendered image changes from fig1 to fig2.
My understanding and modification may be wrong, so how to render images of other resolutions (greater or less than the original resolution). Very much looking forward to your reply!

![1](https://github.com/user-attachments/assets/b198e006-7919-4ef7-bf29-d438ec1b259c)
![2](https://github.com/user-attachments/assets/462b2398-1400-46b5-84c3-5095817b8f20)

**Comment by Xinjie-Q** [comment]
At this time, our work cannot support different resolution rendering due to the introduction of accumulated blending. If you want to support different resolution rendering, please use alpha blending.

**Comment by djx99** [comment]
I am new to 3DGS and know less about it, what is alpha blending? Can you share a relevant link? Thank you so much!

**Comment by Xinjie-Q** [comment]
You can see the alpha blending details: Mathematical Supplement for the gsplat Library.

**Comment by Downchuck** [comment]
EDIT:  Testing these a little further, it's a good hint for upscaling but is incomplete.

I'm not clear if accumulating blending required or the cholesky can be adjusted appropriately - the quick adjustment below is not sufficient.

--

I believe we can just change the model and adjust -- e.g. here is the Cholesky:

```
            #self.gaussian_model.H *= 8
            #self.gaussian_model.W *= 8
            self.gaussian_model.H //= 2
            self.gaussian_model.W //= 2
            self.gaussian_model.tile_bounds = (
                (self.gaussian_model.W + self.gaussian_model.BLOCK_W - 1) // self.gaussian_model.BLOCK_W,
                (self.gaussian_model.H + self.gaussian_model.BLOCK_H - 1) // self.gaussian_model.BLOCK_H,
                1,
            )
            #self.gaussian_model._cholesky *= 8
            self.gaussian_model._cholesky /= 2
            out = self.gaussian_model.forward()
            out_img = out["render"].float()
            transform = transforms.ToPILImage()
            img = transform(out_img.squeeze(0))
            img.save(str("simple.png"))
```
